version: '3.8'

services:
  thelatenight-api:
    container_name: express-api
    build: .
    image: thelatenightshop-api 
    volumes:
      - type: bind
        source: .
        target: /app
      - .env:/app/.env
    ports:
      - "3000:3000"
    env_file:
      - .env
